first commit new master
konqr/lobSimulations pull request #2
Opened 2024-08-04 14:30 UTC by dcuoliveira

2024-08-05 10:18 UTC, konqr requested changes
just need undeleting and moving around of files. rest looks good.

2024-08-05 10:18 UTC, konqr commented on hawkes/simulate_smalltick.py
@dcuoliveira can you pls undelete this file or move it to backup/hawkes?

2024-08-05 10:18 UTC, konqr commented on hawkes/simulate_optimized.py
@dcuoliveira can you pls undelete this file or move it to backup/hawkes?

2024-08-05 10:18 UTC, konqr commented on hawkes/experiments/EDA.ipynb
@dcuoliveira can you pls undelete this file or move it to backup/hawkes/experiments? same applies to all of the files in hawkes/experiments

2024-08-05 10:18 UTC, konqr commented on Benchmarking.ipynb
@dcuoliveira can you pls undelete this file or move it to backup/hawkes/experiments?

2024-08-05 10:18 UTC, konqr commented on hawkes/CreateLOB.py
@dcuoliveira can you pls undelete this file or move it to backup/hawkes? this is an optimized version of the createLOB function

2024-08-05 10:18 UTC, konqr commented on runner.ipynb
@dcuoliveira can you pls undelete this file or move it to backup/hawkes/experiments?

2024-08-05 10:18 UTC, konqr commented on simulated_data/fake_0_0_19_inputRes
@dcuoliveira can you pls undelete this file or move it to backup/hawkes/simulated_data? same for all files under hawkes/simulated_data

2024-08-05 10:18 UTC, konqr commented on src/pricePathsConditionalEvent.ipynb
@dcuoliveira can you pls **delete** this file or move it to backup/hawkes/experiments?

2024-08-05 10:18 UTC, konqr commented on src/runner.ipynb
@dcuoliveira can you pls delete this file or move it to hawkes/drafts?

2024-08-05 10:18 UTC, konqr commented on src/sif_exponential_kernel_mle.ipynb
@dcuoliveira can you pls delete this file or move it to hawkes/drafts?

2024-08-05 10:18 UTC, konqr commented on src/uncertaintyZones.ipynb
@dcuoliveira can you pls delete this file or move it to backup/hawkes/experiments?

2024-08-06 00:29 UTC, dcuoliveira commented
Added missing files and refactored scripts to drafts/backup

2024-08-06 09:20 UTC, konqr approved these changes

2024-08-06 09:21 UTC, merged